# Generated by Django 6.0.2 on 2026-03-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='dias_caducidad',
            field=models.PositiveIntegerField(blank=True, help_text='Días de caducidad desde la compra al distribuidor. Ej: 90 días = 3 meses', null=True),
        ),
    ]
