# Generated by Django 6.0.2 on 2026-05-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_producto_es_fabricable'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(blank=True, help_text='Ej: kg, g, l, ml, unidad', max_length=20, null=True),
        ),
    ]
