# Generated by Django 6.0.2 on 2026-07-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='medio_pago',
            field=models.CharField(choices=[('mercado_pago', 'Mercado Pago'), ('efectivo', 'Efectivo'), ('cuenta_bancaria', 'Cuenta Bancaria')], default='efectivo', max_length=20),
        ),
    ]
