# Generated by Django 6.0.2 on 2026-05-20 02:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('products', '0004_producto_unidad_medida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoCocina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('total_costo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_cocina', to='locations.ubicacion')),
            ],
            options={
                'verbose_name': 'Consumo de cocina',
                'verbose_name_plural': 'Consumos de cocina',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoCocinaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('costo_unitario_momento', models.DecimalField(decimal_places=2, max_digits=12)),
                ('consumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='consumos.consumococina')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.producto')),
                ('sub_ubicacion_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.sububicacion')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
