# Generated by Django 6.0.2 on 2026-07-01 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumos', '0001_initial'),
        ('locations', '0001_initial'),
        ('products', '0004_producto_unidad_medida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduccionVianda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sub_ubicacion_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.sububicacion')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producciones_vianda', to='locations.ubicacion')),
            ],
            options={
                'verbose_name': 'Producción de vianda',
                'verbose_name_plural': 'Producciones de vianda',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ProduccionViandaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_venta_momento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='consumos.produccionvianda')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.producto')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
