# Generated by Django 6.0.2 on 2026-02-10 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('sucursal', 'Sucursal'), ('almacen', 'Almacén Central')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SubUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ambiente', 'Temperatura Ambiente'), ('heladera', 'Heladera'), ('freezer', 'Freezer')], max_length=20)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_ubicaciones', to='locations.ubicacion')),
            ],
        ),
    ]
