# Generated by Django 6.0.2 on 2026-02-17 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sucursal_asignada',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'sucursal'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='locations.ubicacion', verbose_name='Sucursal Asignada'),
        ),
    ]
