# Generated by Django 6.0.2 on 2026-04-23 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_sucursal_asignada'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cuenta_pareada',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pareja_de', to=settings.AUTH_USER_MODEL, verbose_name='Cuenta Pareada'),
        ),
    ]
