# Generated by Django 6.0.2 on 2026-02-10 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='products.producto')),
                ('sub_ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='locations.sububicacion')),
            ],
            options={
                'verbose_name_plural': 'Stocks',
                'unique_together': {('producto', 'sub_ubicacion')},
            },
        ),
    ]
