# Generated by Django 6.0.2 on 2026-02-10 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_pedido_pedidoitem'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='sub_ubicacion_destino',
            field=models.ForeignKey(blank=True, help_text='Donde se guardó el producto al recibirlo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.sububicacion'),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='precio_costo_momento',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
