# Generated by Django 6.0.2 on 2026-02-27 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_pedidoitem_sub_ubicacion_destino_and_more'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='provisto_desde_almacen',
            field=models.BooleanField(default=False, help_text='Indica si el pedido fue provisto desde el almacén del admin'),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='sub_ubicacion_origen',
            field=models.ForeignKey(blank=True, help_text='De donde se tomó el producto en el almacén del admin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_items_origen', to='locations.sububicacion'),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='sub_ubicacion_destino',
            field=models.ForeignKey(blank=True, help_text='Donde se guardó el producto al recibirlo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_items_destino', to='locations.sububicacion'),
        ),
    ]
