# Generated by Django 6.0.2 on 2026-03-04 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_pedido_provisto_desde_almacen_and_more'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='provisto_desde_almacen',
        ),
        migrations.AddField(
            model_name='pedido',
            name='origen_sucursal',
            field=models.ForeignKey(blank=True, help_text="Sucursal/almacén de origen si origen_tipo='sucursal'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_origen', to='locations.ubicacion'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='origen_tipo',
            field=models.CharField(choices=[('distribuidor', 'Distribuidor'), ('sucursal', 'Sucursal')], default='distribuidor', help_text='Origen del stock para este pedido', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_destino', to='locations.ubicacion'),
        ),
    ]
