# Generated by Django 6.0.2 on 2026-03-04 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_pedido_provisto_desde_almacen_and_more'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='sub_ubicaciones_origen_detalle',
            field=models.JSONField(blank=True, help_text='Array de {sub_ubicacion_id, cantidad} cuando el stock se toma de múltiples sub-ubicaciones', null=True),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='sub_ubicacion_origen',
            field=models.ForeignKey(blank=True, help_text='De donde se tomó el producto en el almacén del admin (campo legacy)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_items_origen', to='locations.sububicacion'),
        ),
    ]
