# Generated by Django 6.0.2 on 2026-03-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_pedidoitem_sub_ubicaciones_origen_detalle_and_more'),
        ('locations', '0001_initial'),
        ('products', '0002_producto_dias_caducidad'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stock',
            name='fecha_ingreso',
            field=models.DateField(blank=True, help_text='Fecha de ingreso del lote al stock', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='lote',
            field=models.CharField(blank=True, help_text='Identificador del lote (puede ser generado automáticamente)', max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('producto', 'sub_ubicacion', 'lote')},
        ),
    ]
