# Generated by Django 6.0.2 on 2026-04-21 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_stock_cantidad_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='origen_tipo',
            field=models.CharField(choices=[('distribuidor', 'Distribuidor'), ('sucursal', 'Sucursal'), ('mixto', 'Mixto')], default='distribuidor', help_text='Origen del stock para este pedido', max_length=20),
        ),
    ]
